# Generated by Django 6.1.1 on 2026-10-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['position', '-created_at']},
        ),
        migrations.AddField(
            model_name='article',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
