# Generated by Django 6.1.1 on 2026-10-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_fill_article_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='summary_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='summary_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed')], default='none', max_length=10),
        ),
    ]
